"""Alembic environment for the substrate.

Online mode only. The revisions are hand-written DDL rather than autogenerated from models, so
there is no ``target_metadata``: the schema this package owns is small, deliberate, and includes
policies, functions and triggers that autogeneration cannot see anyway.
"""

from __future__ import annotations

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config


def _url() -> str:
    url = config.attributes.get("connection_url") or config.get_main_option("sqlalchemy.url")
    if not url:
        raise RuntimeError(
            "no database URL was supplied; build the config with "
            "metaframer_kernel_db.migrations.alembic_config(url)"
        )
    return url


def run_migrations_online() -> None:
    engine = create_engine(_url(), poolclass=pool.NullPool, future=True)
    try:
        with engine.connect() as connection:
            context.configure(connection=connection, target_metadata=None)
            with context.begin_transaction():
                context.run_migrations()
    finally:
        engine.dispose()


if context.is_offline_mode():
    raise RuntimeError("offline migrations are not supported by this substrate")
run_migrations_online()
